package com.webssk.maven.plugins;

public class TextToCpp extends TextToCode {

    @Override
    protected StringBuffer getScript() {
        StringBuffer sb = new StringBuffer();
        sb.append("// This is autogenerated file, don't change it manually\n");
        sb.append("// Source file has located at "
                + makeProperty(TextToCppProperties.INPUT_FILE) + "\n");
        sb.append("#include \"StdAfx.h\"\n");
        sb.append("\n");
        sb.append("const char* "
                + makeProperty(TextToCppProperties.VARIABLE_NAME) + " = \n");
        sb.append(makeProperty(TextToCppProperties.TEXT_STRING) + ";\n");
        return sb;
    }

    @Override
    protected String getExt() {
        return ".cpp";
    }

    @Override
    protected Class<? extends TextToCodeProperties> getPropertiesClass() {
        return TextToCppProperties.class;
    }

    public static void main(String[] args) {
        TextToCpp cpp = new TextToCpp();
        TextToCppProperties params = (TextToCppProperties) cpp.getProperties();
        params.setInputFile("test.sql");
        params.setOutputFile("test.cpp");
        params.setStdafxProlog("1");
        params.setVariableName("test");
        cpp.run();
    }
}
