package com.webssk.maven.plugins;

public class TextToPython extends TextToCode {

    @Override
    protected String quoteString(String string) {
        StringBuffer buffer = new StringBuffer();
        buffer.append(string.replaceAll("\\\\", "\\\\\\\\")
                .replaceAll("\"", "\\\\\\\"").replaceAll("\n", "\\\\n"));
        return buffer.toString();
    }

    @Override
    protected StringBuffer getScript() {
        StringBuffer sb = new StringBuffer();
        sb.append("# This is autogenerated file, don't change it manually\n");
        sb.append("# Source file has located at "
                + makeProperty(TextToPythonProperties.INPUT_FILE) + "\n\n");
        sb.append(makeProperty(TextToPythonProperties.VARIABLE_NAME)
                + " = \"\"\"\n");
        sb.append(makeProperty(TextToPythonProperties.TEXT_STRING) + "\"\"\"\n");
        return sb;
    }

    @Override
    protected String getExt() {
        return ".py";
    }

    @Override
    protected Class<? extends TextToCodeProperties> getPropertiesClass() {
        return TextToPythonProperties.class;
    }

    public static void main(String[] args) {
        TextToPython python = new TextToPython();
        TextToPythonProperties params = (TextToPythonProperties) python
                .getProperties();
        params.setInputFile("test.sql");
        params.setOutputFile("test.py");
        params.setVariableName("test");
        python.run();
    }
}
