// This is autogenerated file, don't change it manually
// Source file has located at src/test/resources/test.sql
#include "StdAfx.h"

const char* test = 
    "-- Получить список изданий\n"
    "select t.*\n"
    "  from zx.issues t\n"
    " where t.code in (1, 9);\n";

// vim: set fenc=utf-8 ff=unix
