// This is autogenerated file, don't change it manually
// Source file has located at src/test/resources/test.sql

public final class Test {

    public static final String TEXT =
        "-- Получить список изданий\n" +
        "select t.*\n" +
        "  from zx.issues t\n" +
        " where t.code in (1, 9);\n";

    @Override
    public String toString() {
        return TEXT;
    }
}
